// Add this route to server/routes/students.js
const express = require("express");
const Student = require("../models/Student");
const User = require("../models/User");
const Course = require("../models/Course");
const Activity = require("../models/Activity");
const { auth, authorize } = require("../middleware/auth");
const { body, validationResult } = require("express-validator");

const router = express.Router();

// @desc    Register new student (with user account)
// @route   POST /api/students/register
// @access  Private (Admin)
router.post(
  "/register",
  [
    auth,
    authorize("admin"),
    body("name").trim().notEmpty().withMessage("Name is required"),
    body("email")
      .trim()
      .isEmail()
      .withMessage("Please include a valid email")
      .normalizeEmail(),
    body("password")
      .isLength({ min: 6 })
      .withMessage("Password must be at least 6 characters"),
    body("grade")
      .isIn([
        "Remedial",
        "1st Year",
        "2nd Year",
        "3rd Year",
        "4th Year",
        "5th Year",
      ])
      .withMessage("Invalid grade"),
    body("parentName").trim().notEmpty().withMessage("Parent name is required"),
    body("parentContact")
      .trim()
      .notEmpty()
      .withMessage("Parent contact is required"),
    body("semester")
      .isIn(["1st Semester", "2nd Semester"])
      .withMessage("Invalid semester"),
    body("emergencyContact").optional({ checkFalsy: true }).trim(),
    body("dateOfBirth")
      .optional({ checkFalsy: true })
      .isISO8601()
      .withMessage("Invalid date format"),
    body("course").optional({ checkFalsy: true }).trim(),
    body("department").optional({ checkFalsy: true }).trim(),
  ],
  async (req, res) => {
    let createdUser = null;

    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          message: "Validation failed",
          errors: errors.array(),
        });
      }

      const {
        name,
        email,
        password,
        grade,
        dateOfBirth,
        parentName,
        parentContact,
        address,
        emergencyContact,
        semester,
        course,
        department,
      } = req.body;

      let studentUser = null;

      // Check if user exists
      const existingUser = await User.findOne({ email: email.toLowerCase() });
      if (existingUser) {
        const existingStudent = await Student.findOne({ user: existingUser._id });

        if (existingStudent || existingUser.role !== "student") {
          return res.status(400).json({
            success: false,
            message: "Email already registered",
          });
        }

        existingUser.name = name.trim();
        existingUser.password = password;
        existingUser.role = "student";
        existingUser.isActive = true;
        studentUser = await existingUser.save();
      }

      if (!studentUser) {
        // Create user first
        createdUser = await User.create({
          name: name.trim(),
          email: email.toLowerCase(),
          password,
          role: "student",
        });
        studentUser = createdUser;
      }

      // Create student record — studentId is auto-generated by model pre-save hook
      const student = await Student.create({
        user: studentUser._id,
        name: name.trim(),
        grade,
        dateOfBirth: dateOfBirth ? new Date(dateOfBirth) : new Date("2000-01-01"),
        parentName: parentName.trim(),
        parentContact: parentContact.trim(),
        address: address || {},
        emergencyContact: emergencyContact ? emergencyContact.trim() : parentContact.trim(),
        semester,
        course: course ? course.trim() : "",
        department: department || null,
      });

      await student.populate("user", "name email");

      try {
        await Activity.create({
          type: "student_added",
          description: `Registered structured student: ${name.trim()}`,
          user: req.user ? req.user.name : "Admin",
        });
      } catch (err) { console.error("Activity log error:", err); }

      res.status(201).json({
        success: true,
        data: student,
      });
    } catch (error) {
      console.error("Student registration error:", error);

      // If the user was created but student creation failed, delete that new user.
      if (createdUser) {
        try {
          await User.findByIdAndDelete(createdUser._id);
        } catch (deleteError) {
          console.error("Error cleaning up user:", deleteError);
        }
      }

      res.status(500).json({
        success: false,
        message: "Server error during student registration: " + error.message,
      });
    }
  }
);

// ... rest of your student routes

// @desc    Get available main courses for student registration
// @route   GET /api/students/available-courses
// @access  Private (Admin)
router.get("/available-courses", auth, authorize("admin"), async (req, res) => {
  try {
    // Get distinct course names first
    const distinctCourseNames = await Course.distinct("name", { isActive: true });
    
    console.log(`Found ${distinctCourseNames.length} distinct course names`);
    
    // For each distinct name, get the first course record
    const mainCourses = [];
    
    for (const courseName of distinctCourseNames) {
      const firstCourse = await Course.findOne({ 
        name: courseName, 
        isActive: true 
      }).select("name code description credits");
      
      if (firstCourse) {
        mainCourses.push({
          _id: firstCourse._id,
          name: firstCourse.name,
          code: firstCourse.code.split('-')[0],
          description: firstCourse.description || "Main Course",
          credits: firstCourse.credits
        });
      }
    }
    
    // Sort by name
    mainCourses.sort((a, b) => a.name.localeCompare(b.name));

    console.log(`Returning ${mainCourses.length} unique main courses`);
    
    res.json({
      success: true,
      data: mainCourses,
    });
  } catch (error) {
    console.error("Get available courses error:", error);
    res.status(500).json({
      success: false,
      message: "Error fetching available courses: " + error.message,
    });
  }
});

// @desc    Get all students with pagination
// @route   GET /api/students
// @access  Private (Admin, Teacher)
router.get("/", auth, authorize("admin", "teacher"), async (req, res) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;

    let query = {};
    if (req.user.role === "teacher") {
      const teacherCourses = await Course.find({ teacher: req.user._id });
      if (teacherCourses.length === 0) {
        return res.json({
          success: true,
          data: [],
          pagination: { page, limit, total: 0, pages: 0 },
        });
      }
      
      const enrolledStudentIds = [];
      const courseNames = [];
      
      teacherCourses.forEach(c => {
        if (c.enrolledStudents) enrolledStudentIds.push(...c.enrolledStudents);
        if (c.name) courseNames.push(new RegExp("^" + c.name.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&') + "$", "i"));
      });
      
      query = {
        $or: [
          { _id: { $in: enrolledStudentIds } },
          { course: { $in: courseNames } }
        ]
      };
    }

    const students = await Student.find(query)
      .populate("user", "name email")
      .populate("department", "name")
      .skip(skip)
      .limit(limit)
      .sort({ createdAt: -1 });

    const total = await Student.countDocuments(query);

    res.json({
      success: true,
      data: students,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    console.error("Get students error:", error);
    res.status(500).json({
      success: false,
      message: "Server error while fetching students",
    });
  }
});

// @desc    Get single student
// @route   GET /api/students/:id
// @access  Private
router.get("/:id", auth, async (req, res) => {
  try {
    const student = await Student.findById(req.params.id)
      .populate("user", "name email")
      .populate("department", "name");

    if (!student) {
      return res.status(404).json({
        success: false,
        message: "Student not found",
      });
    }

    // Students can only view their own profile unless admin/teacher
    if (
      req.user.role === "student" &&
      student.user._id.toString() !== req.user._id.toString()
    ) {
      return res.status(403).json({
        success: false,
        message: "Access denied",
      });
    }

    res.json({
      success: true,
      data: student,
    });
  } catch (error) {
    console.error("Get student error:", error);
    res.status(500).json({
      success: false,
      message: "Server error while fetching student",
    });
  }
});

// @desc    Create student
// @route   POST /api/students
// @access  Private (Admin)
router.post(
  "/",
  [
    auth,
    authorize("admin"),
    body("grade")
      .isIn([
        "Remedial",
        "1st Year",
        "2nd Year",
        "3rd Year",
        "4th Year",
        "5th Year",
      ])
      .withMessage("Invalid grade"),
    body("parentName").notEmpty().withMessage("Parent name is required"),
    body("parentContact").notEmpty().withMessage("Parent contact is required"),
    body("semester")
      .isIn(["1st Semester", "2nd Semester"])
      .withMessage("Invalid semester"),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          message: "Validation failed",
          errors: errors.array(),
        });
      }

      const student = await Student.create(req.body);

      await student.populate("user", "name email");

      res.status(201).json({
        success: true,
        data: student,
      });
    } catch (error) {
      console.error("Create student error:", error);
      res.status(500).json({
        success: false,
        message: "Server error while creating student",
      });
    }
  }
);

// @desc    Update student
// @route   PUT /api/students/:id
// @access  Private (Admin)
router.put("/:id", auth, authorize("admin"), async (req, res) => {
  try {
    const student = await Student.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
      runValidators: true,
    }).populate("user", "name email");

    if (!student) {
      return res.status(404).json({
        success: false,
        message: "Student not found",
      });
    }

    res.json({
      success: true,
      data: student,
    });
  } catch (error) {
    console.error("Update student error:", error);
    res.status(500).json({
      success: false,
      message: "Server error while updating student",
    });
  }
});

// @desc    Delete student
// @route   DELETE /api/students/:id
// @access  Private (Admin)
router.delete("/:id", auth, authorize("admin"), async (req, res) => {
  try {
    const student = await Student.findById(req.params.id);

    if (!student) {
      return res.status(404).json({
        success: false,
        message: "Student not found",
      });
    }

    // Also delete the associated user
    await User.findByIdAndDelete(student.user);

    await Student.findByIdAndDelete(req.params.id);

    try {
      await Activity.create({
        type: "student_deleted",
        description: `Deleted student: ${student.name}`,
        user: req.user ? req.user.name : "Admin",
      });
    } catch (err) { console.error("Activity log error:", err); }

    res.json({
      success: true,
      message: "Student deleted successfully",
    });
  } catch (error) {
    console.error("Delete student error:", error);
    res.status(500).json({
      success: false,
      message: "Server error while deleting student",
    });
  }
});

module.exports = router;
